### PR TITLE
Connect and disconnect remote android device

### LINKED ISSUE #103: Disconnect fails when serial is ipaddress:port
Steps:
1. Connect AndroidTV using adb over wifi
2. Check device info 'adb devices'. Output looks like --> ipaddress:port (x.x.x.x:portno)
3. Add device in device_api object (device = DeviceAPI::Android.device(ipaddress:port)
4. Disconnect using device_api object -- > device.disconnect() 

'device.disconnect' doesn't works because ADB.disconnect assumes its just the ipaddress and not ipaddress:port. It adds another port (like ipaddress:port:port) and then fails to disconnect.

### PR DESCRIPTION
**Pull request by Asimk21**
1. Should now able to connect to remote android device from DeviceAPI::Android object
2. Can pass in just ip_address or ip_address and port to connect method
3. Fixes #103

### CODE REVIEW

File: lib/device_api/android/adb.rb [hunk 1]
```diff
@@ -232,28 +232,43 @@ def self.screencap( serial, args )
...
+      # @example
+      #  DeviceAPI::ADB.connect(ip_address, port)  
+      #  DeviceAPI::ADB.connect(ip_address_and_port)
+      def self.connect(ip_address, port=5555)
 
-      def self.connect(ipaddress, port = 5555)
-        ipaddressandport = "#{ipaddress}:#{port}"
-        check_ip_address(ipaddressandport)
-        cmd = "adb connect #{ipaddressandport}"
+        value = ip_address.split(":").last
```
Comment (jonpwilson) [inline lib/device_api/android/adb.rb]: Could we push this to what ever is calling this method please? The ip_address parameter should be just that, if we have a named parameter there shouldn't be any ambiguity as to what is being passed.

File: lib/device_api/android/adb.rb [hunk 2]
```diff
@@ -232,28 +232,43 @@ def self.screencap( serial, args )
...
+        else
+          ip_address_and_port = ip_address
+        end
+
+        check_ip_address(ip_address_and_port)
+        cmd = "adb connect #{ip_address_and_port}"
         result = execute(cmd)
         if result.stdout.to_s =~ /.*already connected to.*/
-          raise DeviceAlreadyConnectedError.new("Device #{ipaddressandport} already connected")
+          raise DeviceAlreadyConnectedError.new("Device #{ip_address_and_port} already connected")
```
Comment (jonpwilson) [inline lib/device_api/android/adb.rb]: :thumbsup:

File: lib/device_api/android/adb.rb (hunk 1 above)
Comment (Asimk21) [inline lib/device_api/android/adb.rb]: Done. Thanks
