### PR TITLE
Screenshot for android 7.0

### LINKED ISSUE #126: Screencap not working on Android 7X
I am experiencing an issue using the `screencap` method of Device API Android on a Nexus 6P although the device appears not to matter.

* Android 6.01 the functionality works correctly.
* Android 7.0 the functionality does not work (an image is generated but it is corrupt).

The issue appears to be with the Perl script that removes the linebreaks in the generated PNG not working for 7X versions of Android.

Many thanks.

### PR DESCRIPTION
**Pull request by Asimk21**
Fix #126 
Battery plugin would return an object instead of an Hash. All previous operations on battery were on hash. Now it is modified to access using '.'

### CODE REVIEW

File: lib/device_api/android/adb.rb [hunk 1]
```diff
@@ -236,10 +236,11 @@ def self.monkey(qualifier, args)
       def self.screencap( qualifier, args )
         
         filename = args[:filename] or raise "filename not provided (:filename => '/tmp/myfile.png')"
-        
+ 
         convert_carriage_returns = %q{perl -pe 's/\x0D\x0A/\x0A/g'}
         cmd = "screencap -p | #{convert_carriage_returns} > #{filename}"
         
+        cmd = "screencap -p" if getprop(qualifier)['ro.build.version.release'].to_i > 6
```
Comment (jrmhaig) [inline lib/device_api/android/adb.rb]: This doesn't appear to write out to `filename`. Also, this and the previous line can be simplified either with an if-then-else or by concatenating the string when version <= 6 instead of setting twice.
